import os
import subprocess
import json
import requests
from pathlib import Path

# ---------------------------------------------------------------------------
# Configuration – read from environment variables
# ---------------------------------------------------------------------------
FB_PAGE_ID = os.getenv("FB_PAGE_ID")  # Facebook Page ID
FB_ACCESS_TOKEN = os.getenv("FB_ACCESS_TOKEN")  # Page Access Token with publish_video permission

if not FB_PAGE_ID or not FB_ACCESS_TOKEN:
    raise RuntimeError("Facebook credentials (FB_PAGE_ID, FB_ACCESS_TOKEN) are not set in the environment.")

# ---------------------------------------------------------------------------
# Helper – run the existing make_reel script to generate shorts_deal.mp4
# ---------------------------------------------------------------------------
def run_make_reel():
    """Execute make_reel.py which creates 'shorts_deal.mp4' and 'youtube_details.txt'."""
    script_path = Path(__file__).parent / "make_reel.py"
    if not script_path.is_file():
        raise FileNotFoundError(f"{script_path} not found")
    # Use the same Python interpreter that runs this script
    subprocess.check_call(["py", "-3", str(script_path)], cwd=script_path.parent)
    video_path = script_path.parent / "shorts_deal.mp4"
    if not video_path.is_file():
        raise FileNotFoundError("Reel generation failed – shorts_deal.mp4 not found")
    return video_path

# ---------------------------------------------------------------------------
# Helper – upload the generated video to YouTube using the existing uploader
# ---------------------------------------------------------------------------
def upload_to_youtube(video_path: Path):
    """Import and invoke the youtube_auto_upload script's main entry point.
    The uploader expects the video file to already exist and reads metadata from
    'youtube_details.txt' which is generated by make_reel.py.
    """
    cwd = video_path.parent
    import importlib.util
    spec = importlib.util.spec_from_file_location("youtube_uploader", cwd / "youtube_auto_upload.py")
    uploader = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(uploader)
    creds = uploader.setup_credentials()
    if not creds:
        raise RuntimeError("Could not set up YouTube credentials")
    metadata = uploader.get_metadata()
    if not metadata:
        raise RuntimeError("YouTube metadata missing")
    video_id = uploader.upload_video(str(video_path), metadata, creds)
    print(f"[YouTube] Uploaded video ID: {video_id}")
    return video_id

# ---------------------------------------------------------------------------
# Helper – post the same video file to Facebook
# ---------------------------------------------------------------------------
def upload_to_facebook(video_path: Path, description: str = ""):
    """Publish a video to the configured Facebook Page via Graph API.
    Endpoint: POST https://graph.facebook.com/v20.0/{page-id}/videos
    """
    url = f"https://graph.facebook.com/v20.0/{FB_PAGE_ID}/videos"
    with open(video_path, "rb") as f:
        files = {"source": f}
        data = {
            "access_token": FB_ACCESS_TOKEN,
            "description": description,
        }
        response = requests.post(url, files=files, data=data)
    response.raise_for_status()
    result = response.json()
    video_id = result.get("id")
    print(f"[Facebook] Uploaded video ID: {video_id}")
    return video_id

# ---------------------------------------------------------------------------
# Main orchestration
# ---------------------------------------------------------------------------
def main():
    video_path = run_make_reel()
    upload_to_youtube(video_path)
    # Extract description from youtube_details.txt if present
    description = ""
    details_path = video_path.parent / "youtube_details.txt"
    if details_path.is_file():
        try:
            content = details_path.read_text(encoding="utf-8")
            parts = content.split("--- YOUTUBE DESCRIPTION ---\n")
            if len(parts) > 1:
                description = parts[1].strip()
        except Exception:
            pass
    upload_to_facebook(video_path, description=description)
    print("✅ All uploads completed successfully.")

if __name__ == "__main__":
    main()
