import os
import json
import re
import time
import httplib2
from googleapiclient.discovery import build
from googleapiclient.errors import HttpError
from googleapiclient.http import MediaFileUpload
from google.oauth2.credentials import Credentials

SCOPES = ["https://www.googleapis.com/auth/youtube.upload"]
MAX_RETRIES = 5
RETRIABLE_STATUS_CODES = [500, 502, 503, 504]

def setup_credentials():
    """Restores client_secrets.json and token.json from environment variables."""
    client_secrets_json = os.getenv("YOUTUBE_CLIENT_SECRETS")
    token_json = os.getenv("YOUTUBE_TOKEN")
    
    if not client_secrets_json or not token_json:
        print("[YouTube Uploader] Error: YOUTUBE_CLIENT_SECRETS or YOUTUBE_TOKEN environment variables are missing!")
        return None
        
    try:
        # Load string contents or parses JSON safely
        secrets_data = json.loads(client_secrets_json)
        token_data = json.loads(token_json)
        
        with open("client_secrets.json", "w", encoding="utf-8") as f:
            json.dump(secrets_data, f)
            
        with open("token.json", "w", encoding="utf-8") as f:
            json.dump(token_data, f)
            
        print("[YouTube Uploader] Successfully restored credentials files from environment variables.")
        return Credentials.from_authorized_user_file("token.json", SCOPES)
    except Exception as e:
        print(f"[YouTube Uploader] Error building credentials files: {e}")
        return None

def get_metadata():
    """Reads metadata from youtube_details.txt generated by make_reel.py."""
    if not os.path.exists("youtube_details.txt"):
        print("[YouTube Uploader] youtube_details.txt not found!")
        return None
        
    try:
        with open("youtube_details.txt", "r", encoding="utf-8") as f:
            content = f.read()
            
        title_match = re.search(r"--- YOUTUBE TITLE ---\n(.*?)\n\n", content, re.DOTALL)
        desc_match = re.search(r"--- YOUTUBE DESCRIPTION ---\n(.*)", content, re.DOTALL)
        
        title = title_match.group(1).strip() if title_match else "Secret Amazon Glitch Deal! #shorts"
        description = desc_match.group(1).strip() if desc_match else "Amazing deals daily!"
        
        # Extract tags from keywords line
        tags = []
        tags_match = re.search(r"Keywords / SEO Tags:\n(.*)", description)
        if tags_match:
            tags = [t.strip() for t in tags_match.group(1).split(",")]
            
        return {
            "title": title[:100], # YouTube limit is 100 chars
            "description": description,
            "tags": tags[:30], # YouTube tags limit
            "category_id": "22" # People & Blogs
        }
    except Exception as e:
        print(f"[YouTube Uploader] Error reading metadata: {e}")
        return None

def upload_video(video_path, metadata, creds):
    """Uploads the video using chunked upload and exponential backoff retry."""
    youtube = build("youtube", "v3", credentials=creds)

    title = metadata.get("title", "Untitled Upload")
    description = metadata.get("description", "")
    tags = metadata.get("tags", [])
    category_id = metadata.get("category_id", "22")

    body = {
        "snippet": {
            "title": title,
            "description": description,
            "tags": tags,
            "categoryId": category_id
        },
        "status": {
            "privacyStatus": "public" # Upload directly as public since we want organic reach!
        }
    }

    # 1MB chunk size (must be a multiple of 256KB)
    chunksize = 1024 * 1024 
    media = MediaFileUpload(video_path, chunksize=chunksize, resumable=True, mimetype="video/*")

    print(f"\n[Upload] Initializing upload for: {os.path.basename(video_path)}")
    print(f"[Upload] Title: {title}")
    
    request = youtube.videos().insert(
        part="snippet,status",
        body=body,
        media_body=media
    )

    response = None
    error = None
    retry = 0

    while response is None:
        try:
            status, response = request.next_chunk()
            if status:
                percent = int(status.progress() * 100)
                print(f"[Upload] Progress: {percent}% complete.")
        except HttpError as e:
            if e.resp.status in RETRIABLE_STATUS_CODES:
                error = e
                retry += 1
            else:
                raise e
        except (httplib2.HttpLib2Error, IOError) as e:
            error = e
            retry += 1

        if error:
            if retry > MAX_RETRIES:
                raise Exception(f"Upload failed after {MAX_RETRIES} attempts. Last error: {error}")
            
            sleep_time = (2 ** retry)
            print(f"[Upload] Network warning: {error}. Retrying in {sleep_time}s (Attempt {retry}/{MAX_RETRIES})...")
            time.sleep(sleep_time)
            error = None

    print(f"[Upload] SUCCESS! YouTube Video ID: {response['id']}")
    return response["id"]

def main():
    creds = setup_credentials()
    if not creds:
        print("[YouTube Uploader] Cancelled. Credentials could not be set up.")
        return
        
    # Generate the video frame & details using make_reel.py
    print("[YouTube Uploader] Generating Shorts video using make_reel.py...")
    try:
        import make_reel
        make_reel.main()
    except Exception as e:
        print(f"[YouTube Uploader] Error running make_reel.py: {e}")
        return
    
    video_path = "shorts_deal.mp4"
    if not os.path.exists(video_path):
        print(f"[YouTube Uploader] Error: {video_path} was not generated!")
        return
        
    metadata = get_metadata()
    if not metadata:
        print("[YouTube Uploader] Error: Could not parse video metadata!")
        return
        
    try:
        upload_video(video_path, metadata, creds)
    except Exception as e:
        print(f"[YouTube Uploader] Critical upload failed: {e}")
    finally:
        # Cleanup credential files for security
        print("[YouTube Uploader] Cleaning up temporary files...")
        for f in ["client_secrets.json", "token.json", "shorts_deal.mp4", "youtube_details.txt", "Oswald-Bold.ttf", "Oswald-Regular.ttf"]:
            if os.path.exists(f):
                try: os.remove(f)
                except Exception as ex:
                    print(f"Could not remove {f}: {ex}")

if __name__ == "__main__":
    main()
